### ISSUE TITLE
Can't post on reddit (yikes)

### ISSUE THREAD

**Issue by n0nag0n** [askonomm/router#3]
Just wanted to leave a comment on Reddit, but I need 1 more comment karma point (oh well). Here's what I was going to say.

I think this is a great learning opportunity for you! It doesn't have to be perfect or handle all cases that anyone can think of. Slim, Laravel, and Symfony have been around for years and they've solved problems I'm confident you've never even dreamed of. I think that's a great idea to focus on performance cause then you can see bottlenecks that you can't see without a certain focus.

As for your library itself, it actually reminds me a lot of how the Mako Framework in PHP does it's dependency injection. When I looked at how they handle things (with their ContainerAware trait and basically everything in their syringe/ directory) it is crazy how simple, yet powerful it is. As you continue to learn I highly recommend you check out Mako to see what you can learn from their approach.

They are at https://makoframework.com if you want to poke around.

**Comment by askonomm** [comment]
This isn't intended to be for learning, but for actually using, in that I use it for my own projects. You bring up a variety of frameworks, but this isn't a framework, this is a HTTP router. I don't intend this to ever be a framework or even to be an equivalent to the mentioned frameworks HTTP routers. 

The main purpose for existing for this particular router is to bring as convenient and comfortable developer experience as possible when doing HTTP routing with configuration-free DI, and that's literally it. I don't want to grow this library bigger than its intention, and once I have implemented the few open issues here, I will call it feature-complete and intend to just do maintenance going forward.

**Comment by n0nag0n** [comment]
I wasn’t saying to make a framework out, more just pointing you towards
ideas on how to flesh your thoughts out more. No harm intended.
